title = "IOAA–Austria"
baseURL = "https://ioaa-austria.at"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "IOAA–Austria"
    weight = 1
    contentDir = "content/de"
    # languageDirection = 'rtl' for Right-To-Left languages
  # [languages.fr]
   #  title = "Ananke Fr"
   #  weight = 2
    # contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/IOAA_Austria_Logo_2.svg"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  site_logo = "images/IOAA_Austria_Logo_2.svg"
  
 [markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"s
