title = "IOAA–Austria"
baseURL = "https://ioaa-austria.at"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
[pagination]
	pagerSize = 10 # this is set low for demonstrating with dummy content. Set to a higher number


[languages]
  [languages.de]
    title = "IOAA–Austria"
    weight = 1
    contentDir = "content/de"
    # languageDirection = 'rtl' for Right-To-Left languages
  # [languages.fr]
   #  title = "Ananke Fr"
   #  weight = 2
    # contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  social = []

[params]
  text_color = ""
  author = ""
  favicon = "images/IOAA_Austria_Logo_2.svg"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  site_logo = "images/IOAA_Austria_Logo_2.svg"
  [[params.ananke_socials]]
  name = "instagram"
  url = "https://www.instagram.com/ioaaaustria/"
  color = "#ffffff"

  [[params.ananke_socials]]
  name = "newsletter"
  url = "https://19bbd83e.sibforms.com/serve/MUIFAPSfjgC4vpZsEk3SwRR8ZI1Yrn6Yy7qfTL5bdSjxptTHznF-wT8fZNAfOYEw7NwIdrytIB7RdzeapqrHNagVmQl24VHgJR4f_LVh1hI_-JXGIFTkxvn6zJDQiSERDcDLW2EeIL6PakefiiNAowLXRE8Nt5aIWouSkxdYhXAUHEt-M9bnm13Fk9Y_gQP0QQB18_FvGA9e_k9b"
  color = "#ffffff"


 [markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"s
